[project]
name = "habidos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rahuldasdv7", email = "dasari.usapp@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "pipecat-ai[deepgram,elevenlabs,twilio,websocket]>=1.8.1",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
habidos = "habidos:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
